services:
  revprox:
    build: ./nginx
    container_name: revprox
    hostname: revprox
    environment:
      - PROXY_SSL=1
      - SERVER_NAME=revprox
      - BACKEND=http://web
      - PARANOIA=4
    ports:
      - "443:443"

  web:
    build: ./httpd
    container_name: web
    hostname: web

  db:
    build: ./postgres
    container_name: db
    hostname: db
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_PASSWORD: S63^oXgRT!d&tQ
      PGDATA: /var/lib/postgresql/data/postgres/