#!/bin/sh
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

# from PHP docs:
# This provides us with a new binary, called php-fpm, and a default configuration file called php-fpm.conf is installed in /etc.
# The defaults in this file should be okay to get you started, but be aware that your distribution may have altered it, or changed its location.

# execute php as subprocess
exec php-fpm8 &

# execute httpd and take over main process
exec httpd -DFOREGROUND "$@"